### ISSUE TITLE
Sumbit to Redex maybe?

### ISSUE THREAD

**Issue by splodingsocks** [jaredramirez/bs-elm#5]
Looks like https://redex.github.io has grown to automatically search non-submitted packages:

<img width="941" alt="safari_2018-02-16 14-42-18 2x" src="https://user-images.githubusercontent.com/1227109/36330613-9b775730-1327-11e8-8ec3-1391bf2c0ae7.png">

but I'm guessing that since reason-elm isn't officially submitted it's greyed out. Also, I wonder why it's labelled as "neglected"?

**Comment by jaredramirez** [comment]
This is a cool tool, I haven't heard of it before. It looks like it was marked as "neglected" because the package.json didn't fit the necessary requirements here: https://redex.github.io/publish.

I've updated package.json to include everything the specify, and submitted a PR adding bs-elm to their list of published packages here: https://github.com/redex/data/pull/5.

This PR will be closed once they accept.

**Comment by jaredramirez** [comment]
bs-elm is on redex here: https://redex.github.io/package/bs-elm. Also, it's no longer labeled as "neglacted".

Thank you for pointing this out to me!

**Comment by splodingsocks** [comment]
👍 👏 👏👏👏👏
